# Generated by Django 5.2.6 on 2025-10-05 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.FloatField()),
                ('sex', models.IntegerField(choices=[(0, 'Female'), (1, 'Male')])),
                ('bmi', models.FloatField()),
                ('systolic_bp', models.FloatField(help_text='Systolic Blood Pressure')),
                ('diastolic_bp', models.FloatField(help_text='Diastolic Blood Pressure')),
                ('hba1c', models.FloatField(help_text='Glycated Hemoglobin')),
                ('fasting_plasma_sugar', models.FloatField()),
                ('postprandial_sugar', models.FloatField()),
                ('family_history', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('onset_age', models.FloatField(help_text='Age when diabetes was diagnosed')),
                ('diabetes_duration', models.FloatField(help_text='Duration in years')),
                ('smoking', models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, 'Ex-smoker')])),
                ('physical_activity', models.IntegerField(choices=[(0, 'Low'), (1, 'Moderate'), (2, 'High')])),
                ('medication_use', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('medication_adherence', models.IntegerField(choices=[(0, 'Poor'), (1, 'Moderate'), (2, 'Good')])),
                ('nephropathy_risk', models.FloatField(blank=True, null=True)),
                ('neuropathy_risk', models.FloatField(blank=True, null=True)),
                ('retinopathy_risk', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
